# Generated by Django 2.0.7 on 2018-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=250)),
                ('location', models.CharField(default='Abia,Nigeria', max_length=250)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
