# Generated by Django 2.0.7 on 2018-08-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180718_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Describe the person in simplest way possible'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=' surname  firstname', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='+234', max_length=15, null=True),
        ),
    ]
