# Generated by Django 2.0.7 on 2018-09-04 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0004_auto_20180902_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Contact',
        ),
    ]
