# Generated by Django 2.0.7 on 2018-09-05 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0005_auto_20180904_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Profile',
        ),
    ]
