# Generated by Django 2.0.7 on 2018-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_auto_20180905_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='+234', max_length=15, null=True),
        ),
    ]
