# Generated by Django 2.0.7 on 2018-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20180909_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nationality',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='+234', max_length=14, null=True),
        ),
    ]
