# Generated by Django 2.0.7 on 2018-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20180924_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
