# Generated by Django 2.0.7 on 2019-05-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_auto_20190520_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='created',
        ),
    ]
